name: Nexus & Dockerhub CI/CD (dev)

on:
  push:
    branches: [ "dev" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'
        server-id: 'nexus-grayroot'

    - uses: s4u/maven-settings-action@v3.0.0
      with:
        servers: |
          [{
              "id": "nexus-grayroot",
              "username": "${{ secrets.NEXUS_USERNAME }}",
              "password": "${{ secrets.NEXUS_PASSWORD }}"
          }]

    - name: Deploy to nexus
      run: mvn -B deploy

    - name: Push the Docker image to Github registry
      run: |
        docker login --username grayr0ot --password ${{secrets.GHCR_PASSWORD}} ghcr.io
        docker build . --tag ghcr.io/grayr0ot/sh-server-service:dev
        docker push ghcr.io/grayr0ot/sh-server-service:dev